services:
  cowrie:
    build: .
    container_name: cowrie-honeypot
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ../data/honeyfs/root/.bash_history:/cowrie/cowrie-git/honeyfs/root/.bash_history
    restart: unless-stopped